/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of account
 * @export
 */
export const AccountType = {
    Checking: 'checking',
    Savings: 'savings',
    Cash: 'cash',
    CreditCard: 'creditCard',
    LineOfCredit: 'lineOfCredit',
    OtherAsset: 'otherAsset',
    OtherLiability: 'otherLiability',
    Mortgage: 'mortgage',
    AutoLoan: 'autoLoan',
    StudentLoan: 'studentLoan',
    PersonalLoan: 'personalLoan',
    MedicalDebt: 'medicalDebt',
    OtherDebt: 'otherDebt'
} as const;
export type AccountType = typeof AccountType[keyof typeof AccountType];


export function AccountTypeFromJSON(json: any): AccountType {
    return AccountTypeFromJSONTyped(json, false);
}

export function AccountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountType {
    return json as AccountType;
}

export function AccountTypeToJSON(value?: AccountType | null): any {
    return value as any;
}

