/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 * 
 * @export
 * @interface AccountsResponseData
 */
export interface AccountsResponseData {
    /**
     * 
     * @type {Array<Account>}
     * @memberof AccountsResponseData
     */
    accounts: Array<Account>;
    /**
     * The knowledge of the server
     * @type {number}
     * @memberof AccountsResponseData
     */
    server_knowledge: number;
}

/**
 * Check if a given object implements the AccountsResponseData interface.
 */
export function instanceOfAccountsResponseData(value: object): value is AccountsResponseData {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if (!('server_knowledge' in value) || value['server_knowledge'] === undefined) return false;
    return true;
}

export function AccountsResponseDataFromJSON(json: any): AccountsResponseData {
    return AccountsResponseDataFromJSONTyped(json, false);
}

export function AccountsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(AccountFromJSON)),
        'server_knowledge': json['server_knowledge'],
    };
}

export function AccountsResponseDataToJSON(json: any): AccountsResponseData {
    return AccountsResponseDataToJSONTyped(json, false);
}

export function AccountsResponseDataToJSONTyped(value?: AccountsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': ((value['accounts'] as Array<any>).map(AccountToJSON)),
        'server_knowledge': value['server_knowledge'],
    };
}

