/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { AccountsResponseData } from './AccountsResponseData';
import {
    AccountsResponseDataFromJSON,
    AccountsResponseDataFromJSONTyped,
    AccountsResponseDataToJSON,
} from './AccountsResponseData';

/**
 * 
 * @export
 * @interface AccountsResponse
 */
export interface AccountsResponse {
    /**
     * 
     * @type {AccountsResponseData}
     * @memberof AccountsResponse
     */
    data: AccountsResponseData;
}

/**
 * Check if a given object implements the AccountsResponse interface.
 */
export function instanceOfAccountsResponse(value: object): value is AccountsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountsResponseFromJSON(json: any): AccountsResponse {
    return AccountsResponseFromJSONTyped(json, false);
}

export function AccountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AccountsResponseDataFromJSON(json['data']),
    };
}

export function AccountsResponseToJSON(value?: AccountsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AccountsResponseDataToJSON(value['data']),
    };
}

