/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface AccountResponseData
 */
export interface AccountResponseData {
    /**
     * 
     * @type {Account}
     * @memberof AccountResponseData
     */
    account: Account;
}

/**
 * Check if a given object implements the AccountResponseData interface.
 */
export function instanceOfAccountResponseData(value: object): value is AccountResponseData {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function AccountResponseDataFromJSON(json: any): AccountResponseData {
    return AccountResponseDataFromJSONTyped(json, false);
}

export function AccountResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'account': AccountFromJSON(json['account']),
    };
}

export function AccountResponseDataToJSON(value?: AccountResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': AccountToJSON(value['account']),
    };
}

