/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CurrencyFormat } from './CurrencyFormat';
import {
    CurrencyFormatFromJSON,
    CurrencyFormatFromJSONTyped,
    CurrencyFormatToJSON,
} from './CurrencyFormat';
import type { DateFormat } from './DateFormat';
import {
    DateFormatFromJSON,
    DateFormatFromJSONTyped,
    DateFormatToJSON,
} from './DateFormat';

/**
 * 
 * @export
 * @interface BudgetSettings
 */
export interface BudgetSettings {
    /**
     * 
     * @type {DateFormat}
     * @memberof BudgetSettings
     */
    date_format: DateFormat | null;
    /**
     * 
     * @type {CurrencyFormat}
     * @memberof BudgetSettings
     */
    currency_format: CurrencyFormat | null;
}

/**
 * Check if a given object implements the BudgetSettings interface.
 */
export function instanceOfBudgetSettings(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date_format" in value;
    isInstance = isInstance && "currency_format" in value;

    return isInstance;
}

export function BudgetSettingsFromJSON(json: any): BudgetSettings {
    return BudgetSettingsFromJSONTyped(json, false);
}

export function BudgetSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date_format': DateFormatFromJSON(json['date_format']),
        'currency_format': CurrencyFormatFromJSON(json['currency_format']),
    };
}

export function BudgetSettingsToJSON(value?: BudgetSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date_format': DateFormatToJSON(value.date_format),
        'currency_format': CurrencyFormatToJSON(value.currency_format),
    };
}

