/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetDetailResponseData } from './BudgetDetailResponseData';
import {
    BudgetDetailResponseDataFromJSON,
    BudgetDetailResponseDataFromJSONTyped,
    BudgetDetailResponseDataToJSON,
} from './BudgetDetailResponseData';

/**
 * 
 * @export
 * @interface BudgetDetailResponse
 */
export interface BudgetDetailResponse {
    /**
     * 
     * @type {BudgetDetailResponseData}
     * @memberof BudgetDetailResponse
     */
    data: BudgetDetailResponseData;
}

/**
 * Check if a given object implements the BudgetDetailResponse interface.
 */
export function instanceOfBudgetDetailResponse(value: object): value is BudgetDetailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BudgetDetailResponseFromJSON(json: any): BudgetDetailResponse {
    return BudgetDetailResponseFromJSONTyped(json, false);
}

export function BudgetDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BudgetDetailResponseDataFromJSON(json['data']),
    };
}

export function BudgetDetailResponseToJSON(value?: BudgetDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': BudgetDetailResponseDataToJSON(value['data']),
    };
}

