/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkResponseDataBulk
 */
export interface BulkResponseDataBulk {
    /**
     * The list of Transaction ids that were created.
     * @type {Array<string>}
     * @memberof BulkResponseDataBulk
     */
    transaction_ids: Array<string>;
    /**
     * If any Transactions were not created because they had an `import_id` matching a transaction already on the same account, the specified import_id(s) will be included in this list.
     * @type {Array<string>}
     * @memberof BulkResponseDataBulk
     */
    duplicate_import_ids: Array<string>;
}

/**
 * Check if a given object implements the BulkResponseDataBulk interface.
 */
export function instanceOfBulkResponseDataBulk(value: object): value is BulkResponseDataBulk {
    if (!('transaction_ids' in value) || value['transaction_ids'] === undefined) return false;
    if (!('duplicate_import_ids' in value) || value['duplicate_import_ids'] === undefined) return false;
    return true;
}

export function BulkResponseDataBulkFromJSON(json: any): BulkResponseDataBulk {
    return BulkResponseDataBulkFromJSONTyped(json, false);
}

export function BulkResponseDataBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkResponseDataBulk {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction_ids': json['transaction_ids'],
        'duplicate_import_ids': json['duplicate_import_ids'],
    };
}

export function BulkResponseDataBulkToJSON(json: any): BulkResponseDataBulk {
    return BulkResponseDataBulkToJSONTyped(json, false);
}

export function BulkResponseDataBulkToJSONTyped(value?: BulkResponseDataBulk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_ids': value['transaction_ids'],
        'duplicate_import_ids': value['duplicate_import_ids'],
    };
}

