/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
 * @export
 * @interface CategoryGoalType
 */
export interface CategoryGoalType {
}

/**
 * Check if a given object implements the CategoryGoalType interface.
 */
export function instanceOfCategoryGoalType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryGoalTypeFromJSON(json: any): CategoryGoalType {
    return CategoryGoalTypeFromJSONTyped(json, false);
}

export function CategoryGoalTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryGoalType {
    return json;
}

export function CategoryGoalTypeToJSON(value?: CategoryGoalType | null): any {
    return value;
}

