/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
 * @export
 * @interface DateFormat
 */
export interface DateFormat {
    /**
     * 
     * @type {string}
     * @memberof DateFormat
     */
    format: string;
}

/**
 * Check if a given object implements the DateFormat interface.
 */
export function instanceOfDateFormat(value: object): value is DateFormat {
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function DateFormatFromJSON(json: any): DateFormat {
    return DateFormatFromJSONTyped(json, false);
}

export function DateFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'],
    };
}

export function DateFormatToJSON(json: any): DateFormat {
    return DateFormatToJSONTyped(json, false);
}

export function DateFormatToJSONTyped(value?: DateFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
    };
}

