/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExistingCategory
 */
export interface ExistingCategory {
    /**
     * 
     * @type {string}
     * @memberof ExistingCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExistingCategory
     */
    note?: string;
    /**
     * The id of the category group to which this category belongs.  An internal category group may not be specified.
     * @type {string}
     * @memberof ExistingCategory
     */
    category_group_id?: string;
    /**
     * The goal target amount in milliunits format.  If value is specified and goal has not already been configured for category, a monthly goal will be created for the category with this target amount.  If goal_type is not specified, it will default to 'NEED' or 'MF' for Credit Card Payment categories.
     * @type {number}
     * @memberof ExistingCategory
     */
    goal_target?: number;
    /**
     * The goal target date in ISO format (e.g. 2016-12-01).
     * @type {string}
     * @memberof ExistingCategory
     */
    goal_target_date?: string;
    /**
     * Whether the goal requires the full target amount each period. Only supported for 'NEED' goals. When true, the goal is configured as 'Set aside another...'. When false, the goal is configured as 'Refill up to...'.
     * @type {boolean}
     * @memberof ExistingCategory
     */
    goal_needs_whole_amount?: boolean;
}

/**
 * Check if a given object implements the ExistingCategory interface.
 */
export function instanceOfExistingCategory(value: object): value is ExistingCategory {
    return true;
}

export function ExistingCategoryFromJSON(json: any): ExistingCategory {
    return ExistingCategoryFromJSONTyped(json, false);
}

export function ExistingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExistingCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'category_group_id': json['category_group_id'] == null ? undefined : json['category_group_id'],
        'goal_target': json['goal_target'] == null ? undefined : json['goal_target'],
        'goal_target_date': json['goal_target_date'] == null ? undefined : json['goal_target_date'],
        'goal_needs_whole_amount': json['goal_needs_whole_amount'] == null ? undefined : json['goal_needs_whole_amount'],
    };
}

export function ExistingCategoryToJSON(json: any): ExistingCategory {
    return ExistingCategoryToJSONTyped(json, false);
}

export function ExistingCategoryToJSONTyped(value?: ExistingCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'note': value['note'],
        'category_group_id': value['category_group_id'],
        'goal_target': value['goal_target'],
        'goal_target_date': value['goal_target_date'],
        'goal_needs_whole_amount': value['goal_needs_whole_amount'],
    };
}

