/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { MoneyMovement } from './MoneyMovement';
import {
    MoneyMovementFromJSON,
    MoneyMovementFromJSONTyped,
    MoneyMovementToJSON,
    MoneyMovementToJSONTyped,
} from './MoneyMovement';

/**
 * 
 * @export
 * @interface MoneyMovementsResponseData
 */
export interface MoneyMovementsResponseData {
    /**
     * 
     * @type {Array<MoneyMovement>}
     * @memberof MoneyMovementsResponseData
     */
    money_movements: Array<MoneyMovement>;
    /**
     * The knowledge of the server
     * @type {number}
     * @memberof MoneyMovementsResponseData
     */
    server_knowledge: number;
}

/**
 * Check if a given object implements the MoneyMovementsResponseData interface.
 */
export function instanceOfMoneyMovementsResponseData(value: object): value is MoneyMovementsResponseData {
    if (!('money_movements' in value) || value['money_movements'] === undefined) return false;
    if (!('server_knowledge' in value) || value['server_knowledge'] === undefined) return false;
    return true;
}

export function MoneyMovementsResponseDataFromJSON(json: any): MoneyMovementsResponseData {
    return MoneyMovementsResponseDataFromJSONTyped(json, false);
}

export function MoneyMovementsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyMovementsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'money_movements': ((json['money_movements'] as Array<any>).map(MoneyMovementFromJSON)),
        'server_knowledge': json['server_knowledge'],
    };
}

export function MoneyMovementsResponseDataToJSON(json: any): MoneyMovementsResponseData {
    return MoneyMovementsResponseDataToJSONTyped(json, false);
}

export function MoneyMovementsResponseDataToJSONTyped(value?: MoneyMovementsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'money_movements': ((value['money_movements'] as Array<any>).map(MoneyMovementToJSON)),
        'server_knowledge': value['server_knowledge'],
    };
}

