/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyMovementBase
 */
export interface MoneyMovementBase {
    /**
     * 
     * @type {string}
     * @memberof MoneyMovementBase
     */
    id: string;
    /**
     * The month of the money movement in ISO format (e.g. 2024-01-01)
     * @type {string}
     * @memberof MoneyMovementBase
     */
    month?: string | null;
    /**
     * The date/time the money movement was processed on the server in ISO format (e.g. 2024-01-01T12:00:00Z)
     * @type {string}
     * @memberof MoneyMovementBase
     */
    moved_at?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MoneyMovementBase
     */
    note?: string | null;
    /**
     * The id of the money movement group this movement belongs to
     * @type {string}
     * @memberof MoneyMovementBase
     */
    money_movement_group_id?: string | null;
    /**
     * The id of the user who performed the money movement
     * @type {string}
     * @memberof MoneyMovementBase
     */
    performed_by_user_id?: string | null;
    /**
     * The id of the category the money was moved from
     * @type {string}
     * @memberof MoneyMovementBase
     */
    from_category_id?: string | null;
    /**
     * The id of the category the money was moved to
     * @type {string}
     * @memberof MoneyMovementBase
     */
    to_category_id?: string | null;
    /**
     * The amount of the money movement in milliunits format
     * @type {number}
     * @memberof MoneyMovementBase
     */
    amount: number;
}

/**
 * Check if a given object implements the MoneyMovementBase interface.
 */
export function instanceOfMoneyMovementBase(value: object): value is MoneyMovementBase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function MoneyMovementBaseFromJSON(json: any): MoneyMovementBase {
    return MoneyMovementBaseFromJSONTyped(json, false);
}

export function MoneyMovementBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyMovementBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'month': json['month'] == null ? undefined : json['month'],
        'moved_at': json['moved_at'] == null ? undefined : json['moved_at'],
        'note': json['note'] == null ? undefined : json['note'],
        'money_movement_group_id': json['money_movement_group_id'] == null ? undefined : json['money_movement_group_id'],
        'performed_by_user_id': json['performed_by_user_id'] == null ? undefined : json['performed_by_user_id'],
        'from_category_id': json['from_category_id'] == null ? undefined : json['from_category_id'],
        'to_category_id': json['to_category_id'] == null ? undefined : json['to_category_id'],
        'amount': json['amount'],
    };
}

export function MoneyMovementBaseToJSON(json: any): MoneyMovementBase {
    return MoneyMovementBaseToJSONTyped(json, false);
}

export function MoneyMovementBaseToJSONTyped(value?: MoneyMovementBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'month': value['month'],
        'moved_at': value['moved_at'],
        'note': value['note'],
        'money_movement_group_id': value['money_movement_group_id'],
        'performed_by_user_id': value['performed_by_user_id'],
        'from_category_id': value['from_category_id'],
        'to_category_id': value['to_category_id'],
        'amount': value['amount'],
    };
}

