/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { MoneyMovementGroupsResponseData } from './MoneyMovementGroupsResponseData';
import {
    MoneyMovementGroupsResponseDataFromJSON,
    MoneyMovementGroupsResponseDataFromJSONTyped,
    MoneyMovementGroupsResponseDataToJSON,
    MoneyMovementGroupsResponseDataToJSONTyped,
} from './MoneyMovementGroupsResponseData';

/**
 * 
 * @export
 * @interface MoneyMovementGroupsResponse
 */
export interface MoneyMovementGroupsResponse {
    /**
     * 
     * @type {MoneyMovementGroupsResponseData}
     * @memberof MoneyMovementGroupsResponse
     */
    data: MoneyMovementGroupsResponseData;
}

/**
 * Check if a given object implements the MoneyMovementGroupsResponse interface.
 */
export function instanceOfMoneyMovementGroupsResponse(value: object): value is MoneyMovementGroupsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MoneyMovementGroupsResponseFromJSON(json: any): MoneyMovementGroupsResponse {
    return MoneyMovementGroupsResponseFromJSONTyped(json, false);
}

export function MoneyMovementGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyMovementGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': MoneyMovementGroupsResponseDataFromJSON(json['data']),
    };
}

export function MoneyMovementGroupsResponseToJSON(json: any): MoneyMovementGroupsResponse {
    return MoneyMovementGroupsResponseToJSONTyped(json, false);
}

export function MoneyMovementGroupsResponseToJSONTyped(value?: MoneyMovementGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MoneyMovementGroupsResponseDataToJSON(value['data']),
    };
}

