/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyMovementGroup
 */
export interface MoneyMovementGroup {
    /**
     * 
     * @type {string}
     * @memberof MoneyMovementGroup
     */
    id: string;
    /**
     * When the money movement group was created
     * @type {string}
     * @memberof MoneyMovementGroup
     */
    group_created_at: string;
    /**
     * The month of the money movement group in ISO format (e.g. 2024-01-01)
     * @type {string}
     * @memberof MoneyMovementGroup
     */
    month: string;
    /**
     * 
     * @type {string}
     * @memberof MoneyMovementGroup
     */
    note?: string | null;
    /**
     * The id of the user who performed the money movement group
     * @type {string}
     * @memberof MoneyMovementGroup
     */
    performed_by_user_id?: string | null;
}

/**
 * Check if a given object implements the MoneyMovementGroup interface.
 */
export function instanceOfMoneyMovementGroup(value: object): value is MoneyMovementGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('group_created_at' in value) || value['group_created_at'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    return true;
}

export function MoneyMovementGroupFromJSON(json: any): MoneyMovementGroup {
    return MoneyMovementGroupFromJSONTyped(json, false);
}

export function MoneyMovementGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyMovementGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'group_created_at': json['group_created_at'],
        'month': json['month'],
        'note': json['note'] == null ? undefined : json['note'],
        'performed_by_user_id': json['performed_by_user_id'] == null ? undefined : json['performed_by_user_id'],
    };
}

export function MoneyMovementGroupToJSON(json: any): MoneyMovementGroup {
    return MoneyMovementGroupToJSONTyped(json, false);
}

export function MoneyMovementGroupToJSONTyped(value?: MoneyMovementGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'group_created_at': value['group_created_at'],
        'month': value['month'],
        'note': value['note'],
        'performed_by_user_id': value['performed_by_user_id'],
    };
}

