/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { MonthDetail } from './MonthDetail';
import {
    MonthDetailFromJSON,
    MonthDetailFromJSONTyped,
    MonthDetailToJSON,
    MonthDetailToJSONTyped,
} from './MonthDetail';

/**
 * 
 * @export
 * @interface MonthDetailResponseData
 */
export interface MonthDetailResponseData {
    /**
     * 
     * @type {MonthDetail}
     * @memberof MonthDetailResponseData
     */
    month: MonthDetail;
}

/**
 * Check if a given object implements the MonthDetailResponseData interface.
 */
export function instanceOfMonthDetailResponseData(value: object): value is MonthDetailResponseData {
    if (!('month' in value) || value['month'] === undefined) return false;
    return true;
}

export function MonthDetailResponseDataFromJSON(json: any): MonthDetailResponseData {
    return MonthDetailResponseDataFromJSONTyped(json, false);
}

export function MonthDetailResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthDetailResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'month': MonthDetailFromJSON(json['month']),
    };
}

export function MonthDetailResponseDataToJSON(json: any): MonthDetailResponseData {
    return MonthDetailResponseDataToJSONTyped(json, false);
}

export function MonthDetailResponseDataToJSONTyped(value?: MonthDetailResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': MonthDetailToJSON(value['month']),
    };
}

