/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonthSummary
 */
export interface MonthSummary {
    /**
     * 
     * @type {string}
     * @memberof MonthSummary
     */
    month: string;
    /**
     * 
     * @type {string}
     * @memberof MonthSummary
     */
    note?: string;
    /**
     * The total amount of transactions categorized to 'Inflow: Ready to Assign' in the month
     * @type {number}
     * @memberof MonthSummary
     */
    income: number;
    /**
     * The total amount assigned (budgeted) in the month
     * @type {number}
     * @memberof MonthSummary
     */
    budgeted: number;
    /**
     * The total amount of transactions in the month, excluding those categorized to 'Inflow: Ready to Assign'
     * @type {number}
     * @memberof MonthSummary
     */
    activity: number;
    /**
     * The available amount for 'Ready to Assign'
     * @type {number}
     * @memberof MonthSummary
     */
    to_be_budgeted: number;
    /**
     * The Age of Money as of the month
     * @type {number}
     * @memberof MonthSummary
     */
    age_of_money?: number;
    /**
     * Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
     * @type {boolean}
     * @memberof MonthSummary
     */
    deleted: boolean;
    /**
     * The total income formatted in the plan's currency format
     * @type {string}
     * @memberof MonthSummary
     */
    income_formatted?: string;
    /**
     * The total income as a decimal currency amount
     * @type {number}
     * @memberof MonthSummary
     */
    income_currency?: number;
    /**
     * The total amount assigned formatted in the plan's currency format
     * @type {string}
     * @memberof MonthSummary
     */
    budgeted_formatted?: string;
    /**
     * The total amount assigned as a decimal currency amount
     * @type {number}
     * @memberof MonthSummary
     */
    budgeted_currency?: number;
    /**
     * The total activity amount formatted in the plan's currency format
     * @type {string}
     * @memberof MonthSummary
     */
    activity_formatted?: string;
    /**
     * The total activity amount as a decimal currency amount
     * @type {number}
     * @memberof MonthSummary
     */
    activity_currency?: number;
    /**
     * The available amount for 'Ready to Assign' formatted in the plan's currency format
     * @type {string}
     * @memberof MonthSummary
     */
    to_be_budgeted_formatted?: string;
    /**
     * The available amount for 'Ready to Assign' as a decimal currency amount
     * @type {number}
     * @memberof MonthSummary
     */
    to_be_budgeted_currency?: number;
}

/**
 * Check if a given object implements the MonthSummary interface.
 */
export function instanceOfMonthSummary(value: object): value is MonthSummary {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('budgeted' in value) || value['budgeted'] === undefined) return false;
    if (!('activity' in value) || value['activity'] === undefined) return false;
    if (!('to_be_budgeted' in value) || value['to_be_budgeted'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function MonthSummaryFromJSON(json: any): MonthSummary {
    return MonthSummaryFromJSONTyped(json, false);
}

export function MonthSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'],
        'note': json['note'] == null ? undefined : json['note'],
        'income': json['income'],
        'budgeted': json['budgeted'],
        'activity': json['activity'],
        'to_be_budgeted': json['to_be_budgeted'],
        'age_of_money': json['age_of_money'] == null ? undefined : json['age_of_money'],
        'deleted': json['deleted'],
        'income_formatted': json['income_formatted'] == null ? undefined : json['income_formatted'],
        'income_currency': json['income_currency'] == null ? undefined : json['income_currency'],
        'budgeted_formatted': json['budgeted_formatted'] == null ? undefined : json['budgeted_formatted'],
        'budgeted_currency': json['budgeted_currency'] == null ? undefined : json['budgeted_currency'],
        'activity_formatted': json['activity_formatted'] == null ? undefined : json['activity_formatted'],
        'activity_currency': json['activity_currency'] == null ? undefined : json['activity_currency'],
        'to_be_budgeted_formatted': json['to_be_budgeted_formatted'] == null ? undefined : json['to_be_budgeted_formatted'],
        'to_be_budgeted_currency': json['to_be_budgeted_currency'] == null ? undefined : json['to_be_budgeted_currency'],
    };
}

export function MonthSummaryToJSON(json: any): MonthSummary {
    return MonthSummaryToJSONTyped(json, false);
}

export function MonthSummaryToJSONTyped(value?: MonthSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'note': value['note'],
        'income': value['income'],
        'budgeted': value['budgeted'],
        'activity': value['activity'],
        'to_be_budgeted': value['to_be_budgeted'],
        'age_of_money': value['age_of_money'],
        'deleted': value['deleted'],
        'income_formatted': value['income_formatted'],
        'income_currency': value['income_currency'],
        'budgeted_formatted': value['budgeted_formatted'],
        'budgeted_currency': value['budgeted_currency'],
        'activity_formatted': value['activity_formatted'],
        'activity_currency': value['activity_currency'],
        'to_be_budgeted_formatted': value['to_be_budgeted_formatted'],
        'to_be_budgeted_currency': value['to_be_budgeted_currency'],
    };
}

