/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonthDetailResponseData } from './MonthDetailResponseData';
import {
    MonthDetailResponseDataFromJSON,
    MonthDetailResponseDataFromJSONTyped,
    MonthDetailResponseDataToJSON,
} from './MonthDetailResponseData';

/**
 * 
 * @export
 * @interface MonthDetailResponse
 */
export interface MonthDetailResponse {
    /**
     * 
     * @type {MonthDetailResponseData}
     * @memberof MonthDetailResponse
     */
    data: MonthDetailResponseData;
}

/**
 * Check if a given object implements the MonthDetailResponse interface.
 */
export function instanceOfMonthDetailResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function MonthDetailResponseFromJSON(json: any): MonthDetailResponse {
    return MonthDetailResponseFromJSONTyped(json, false);
}

export function MonthDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthDetailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': MonthDetailResponseDataFromJSON(json['data']),
    };
}

export function MonthDetailResponseToJSON(value?: MonthDetailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': MonthDetailResponseDataToJSON(value.data),
    };
}

