/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PayeeLocation } from './PayeeLocation';
import {
    PayeeLocationFromJSON,
    PayeeLocationFromJSONTyped,
    PayeeLocationToJSON,
} from './PayeeLocation';

/**
 * 
 * @export
 * @interface PayeeLocationResponseData
 */
export interface PayeeLocationResponseData {
    /**
     * 
     * @type {PayeeLocation}
     * @memberof PayeeLocationResponseData
     */
    payee_location: PayeeLocation;
}

/**
 * Check if a given object implements the PayeeLocationResponseData interface.
 */
export function instanceOfPayeeLocationResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "payee_location" in value;

    return isInstance;
}

export function PayeeLocationResponseDataFromJSON(json: any): PayeeLocationResponseData {
    return PayeeLocationResponseDataFromJSONTyped(json, false);
}

export function PayeeLocationResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeeLocationResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payee_location': PayeeLocationFromJSON(json['payee_location']),
    };
}

export function PayeeLocationResponseDataToJSON(value?: PayeeLocationResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payee_location': PayeeLocationToJSON(value.payee_location),
    };
}

