/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Payee } from './Payee';
import {
    PayeeFromJSON,
    PayeeFromJSONTyped,
    PayeeToJSON,
} from './Payee';

/**
 * 
 * @export
 * @interface PayeeResponseData
 */
export interface PayeeResponseData {
    /**
     * 
     * @type {Payee}
     * @memberof PayeeResponseData
     */
    payee: Payee;
}

/**
 * Check if a given object implements the PayeeResponseData interface.
 */
export function instanceOfPayeeResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "payee" in value;

    return isInstance;
}

export function PayeeResponseDataFromJSON(json: any): PayeeResponseData {
    return PayeeResponseDataFromJSONTyped(json, false);
}

export function PayeeResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeeResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payee': PayeeFromJSON(json['payee']),
    };
}

export function PayeeResponseDataToJSON(value?: PayeeResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payee': PayeeToJSON(value.payee),
    };
}

