/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { PayeesResponseData } from './PayeesResponseData';
import {
    PayeesResponseDataFromJSON,
    PayeesResponseDataFromJSONTyped,
    PayeesResponseDataToJSON,
    PayeesResponseDataToJSONTyped,
} from './PayeesResponseData';

/**
 * 
 * @export
 * @interface PayeesResponse
 */
export interface PayeesResponse {
    /**
     * 
     * @type {PayeesResponseData}
     * @memberof PayeesResponse
     */
    data: PayeesResponseData;
}

/**
 * Check if a given object implements the PayeesResponse interface.
 */
export function instanceOfPayeesResponse(value: object): value is PayeesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PayeesResponseFromJSON(json: any): PayeesResponse {
    return PayeesResponseFromJSONTyped(json, false);
}

export function PayeesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PayeesResponseDataFromJSON(json['data']),
    };
}

export function PayeesResponseToJSON(json: any): PayeesResponse {
    return PayeesResponseToJSONTyped(json, false);
}

export function PayeesResponseToJSONTyped(value?: PayeesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PayeesResponseDataToJSON(value['data']),
    };
}

