/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Payee } from './Payee';
import {
    PayeeFromJSON,
    PayeeFromJSONTyped,
    PayeeToJSON,
} from './Payee';

/**
 * 
 * @export
 * @interface PayeesResponseData
 */
export interface PayeesResponseData {
    /**
     * 
     * @type {Array<Payee>}
     * @memberof PayeesResponseData
     */
    payees: Array<Payee>;
    /**
     * The knowledge of the server
     * @type {number}
     * @memberof PayeesResponseData
     */
    server_knowledge: number;
}

/**
 * Check if a given object implements the PayeesResponseData interface.
 */
export function instanceOfPayeesResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "payees" in value;
    isInstance = isInstance && "server_knowledge" in value;

    return isInstance;
}

export function PayeesResponseDataFromJSON(json: any): PayeesResponseData {
    return PayeesResponseDataFromJSONTyped(json, false);
}

export function PayeesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeesResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payees': ((json['payees'] as Array<any>).map(PayeeFromJSON)),
        'server_knowledge': json['server_knowledge'],
    };
}

export function PayeesResponseDataToJSON(value?: PayeesResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payees': ((value.payees as Array<any>).map(PayeeToJSON)),
        'server_knowledge': value.server_knowledge,
    };
}

