/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PayeesResponseData } from './PayeesResponseData';
import {
    PayeesResponseDataFromJSON,
    PayeesResponseDataFromJSONTyped,
    PayeesResponseDataToJSON,
} from './PayeesResponseData';

/**
 * 
 * @export
 * @interface PayeesResponse
 */
export interface PayeesResponse {
    /**
     * 
     * @type {PayeesResponseData}
     * @memberof PayeesResponse
     */
    data: PayeesResponseData;
}

/**
 * Check if a given object implements the PayeesResponse interface.
 */
export function instanceOfPayeesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PayeesResponseFromJSON(json: any): PayeesResponse {
    return PayeesResponseFromJSONTyped(json, false);
}

export function PayeesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': PayeesResponseDataFromJSON(json['data']),
    };
}

export function PayeesResponseToJSON(value?: PayeesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PayeesResponseDataToJSON(value.data),
    };
}

