/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayeeLocation
 */
export interface PayeeLocation {
    /**
     * 
     * @type {string}
     * @memberof PayeeLocation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PayeeLocation
     */
    payee_id: string;
    /**
     * 
     * @type {string}
     * @memberof PayeeLocation
     */
    latitude: string;
    /**
     * 
     * @type {string}
     * @memberof PayeeLocation
     */
    longitude: string;
    /**
     * Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
     * @type {boolean}
     * @memberof PayeeLocation
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the PayeeLocation interface.
 */
export function instanceOfPayeeLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "payee_id" in value;
    isInstance = isInstance && "latitude" in value;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "deleted" in value;

    return isInstance;
}

export function PayeeLocationFromJSON(json: any): PayeeLocation {
    return PayeeLocationFromJSONTyped(json, false);
}

export function PayeeLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayeeLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'payee_id': json['payee_id'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'deleted': json['deleted'],
    };
}

export function PayeeLocationToJSON(value?: PayeeLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'payee_id': value.payee_id,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'deleted': value.deleted,
    };
}

