/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { CurrencyFormat } from './CurrencyFormat';
import {
    CurrencyFormatFromJSON,
    CurrencyFormatFromJSONTyped,
    CurrencyFormatToJSON,
    CurrencyFormatToJSONTyped,
} from './CurrencyFormat';
import type { DateFormat } from './DateFormat';
import {
    DateFormatFromJSON,
    DateFormatFromJSONTyped,
    DateFormatToJSON,
    DateFormatToJSONTyped,
} from './DateFormat';

/**
 * 
 * @export
 * @interface PlanSummary
 */
export interface PlanSummary {
    /**
     * 
     * @type {string}
     * @memberof PlanSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlanSummary
     */
    name: string;
    /**
     * The last time any changes were made to the plan from either a web or mobile client
     * @type {string}
     * @memberof PlanSummary
     */
    last_modified_on?: string;
    /**
     * The earliest plan month
     * @type {string}
     * @memberof PlanSummary
     */
    first_month?: string;
    /**
     * The latest plan month
     * @type {string}
     * @memberof PlanSummary
     */
    last_month?: string;
    /**
     * 
     * @type {DateFormat}
     * @memberof PlanSummary
     */
    date_format?: DateFormat;
    /**
     * 
     * @type {CurrencyFormat}
     * @memberof PlanSummary
     */
    currency_format?: CurrencyFormat;
    /**
     * The plan accounts (only included if `include_accounts=true` specified as query parameter)
     * @type {Array<Account>}
     * @memberof PlanSummary
     */
    accounts?: Array<Account>;
}

/**
 * Check if a given object implements the PlanSummary interface.
 */
export function instanceOfPlanSummary(value: object): value is PlanSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PlanSummaryFromJSON(json: any): PlanSummary {
    return PlanSummaryFromJSONTyped(json, false);
}

export function PlanSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'last_modified_on': json['last_modified_on'] == null ? undefined : json['last_modified_on'],
        'first_month': json['first_month'] == null ? undefined : json['first_month'],
        'last_month': json['last_month'] == null ? undefined : json['last_month'],
        'date_format': json['date_format'] == null ? undefined : DateFormatFromJSON(json['date_format']),
        'currency_format': json['currency_format'] == null ? undefined : CurrencyFormatFromJSON(json['currency_format']),
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(AccountFromJSON)),
    };
}

export function PlanSummaryToJSON(json: any): PlanSummary {
    return PlanSummaryToJSONTyped(json, false);
}

export function PlanSummaryToJSONTyped(value?: PlanSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'last_modified_on': value['last_modified_on'],
        'first_month': value['first_month'],
        'last_month': value['last_month'],
        'date_format': DateFormatToJSON(value['date_format']),
        'currency_format': CurrencyFormatToJSON(value['currency_format']),
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(AccountToJSON)),
    };
}

