/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { PlanSummary } from './PlanSummary';
import {
    PlanSummaryFromJSON,
    PlanSummaryFromJSONTyped,
    PlanSummaryToJSON,
    PlanSummaryToJSONTyped,
} from './PlanSummary';

/**
 * 
 * @export
 * @interface PlanSummaryResponseData
 */
export interface PlanSummaryResponseData {
    /**
     * 
     * @type {Array<PlanSummary>}
     * @memberof PlanSummaryResponseData
     */
    plans: Array<PlanSummary>;
    /**
     * 
     * @type {PlanSummary}
     * @memberof PlanSummaryResponseData
     */
    default_plan?: PlanSummary;
}

/**
 * Check if a given object implements the PlanSummaryResponseData interface.
 */
export function instanceOfPlanSummaryResponseData(value: object): value is PlanSummaryResponseData {
    if (!('plans' in value) || value['plans'] === undefined) return false;
    return true;
}

export function PlanSummaryResponseDataFromJSON(json: any): PlanSummaryResponseData {
    return PlanSummaryResponseDataFromJSONTyped(json, false);
}

export function PlanSummaryResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanSummaryResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'plans': ((json['plans'] as Array<any>).map(PlanSummaryFromJSON)),
        'default_plan': json['default_plan'] == null ? undefined : PlanSummaryFromJSON(json['default_plan']),
    };
}

export function PlanSummaryResponseDataToJSON(json: any): PlanSummaryResponseData {
    return PlanSummaryResponseDataToJSONTyped(json, false);
}

export function PlanSummaryResponseDataToJSONTyped(value?: PlanSummaryResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plans': ((value['plans'] as Array<any>).map(PlanSummaryToJSON)),
        'default_plan': PlanSummaryToJSON(value['default_plan']),
    };
}

