/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { PlanDetail } from './PlanDetail';
import {
    PlanDetailFromJSON,
    PlanDetailFromJSONTyped,
    PlanDetailToJSON,
    PlanDetailToJSONTyped,
} from './PlanDetail';

/**
 * 
 * @export
 * @interface PlanDetailResponseData
 */
export interface PlanDetailResponseData {
    /**
     * 
     * @type {PlanDetail}
     * @memberof PlanDetailResponseData
     */
    budget: PlanDetail;
    /**
     * The knowledge of the server
     * @type {number}
     * @memberof PlanDetailResponseData
     */
    server_knowledge: number;
}

/**
 * Check if a given object implements the PlanDetailResponseData interface.
 */
export function instanceOfPlanDetailResponseData(value: object): value is PlanDetailResponseData {
    if (!('budget' in value) || value['budget'] === undefined) return false;
    if (!('server_knowledge' in value) || value['server_knowledge'] === undefined) return false;
    return true;
}

export function PlanDetailResponseDataFromJSON(json: any): PlanDetailResponseData {
    return PlanDetailResponseDataFromJSONTyped(json, false);
}

export function PlanDetailResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanDetailResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'budget': PlanDetailFromJSON(json['budget']),
        'server_knowledge': json['server_knowledge'],
    };
}

export function PlanDetailResponseDataToJSON(json: any): PlanDetailResponseData {
    return PlanDetailResponseDataToJSONTyped(json, false);
}

export function PlanDetailResponseDataToJSONTyped(value?: PlanDetailResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget': PlanDetailToJSON(value['budget']),
        'server_knowledge': value['server_knowledge'],
    };
}

