/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { SaveAccount } from './SaveAccount';
import {
    SaveAccountFromJSON,
    SaveAccountFromJSONTyped,
    SaveAccountToJSON,
} from './SaveAccount';

/**
 * 
 * @export
 * @interface PostAccountWrapper
 */
export interface PostAccountWrapper {
    /**
     * 
     * @type {SaveAccount}
     * @memberof PostAccountWrapper
     */
    account: SaveAccount;
}

/**
 * Check if a given object implements the PostAccountWrapper interface.
 */
export function instanceOfPostAccountWrapper(value: object): value is PostAccountWrapper {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function PostAccountWrapperFromJSON(json: any): PostAccountWrapper {
    return PostAccountWrapperFromJSONTyped(json, false);
}

export function PostAccountWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAccountWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'account': SaveAccountFromJSON(json['account']),
    };
}

export function PostAccountWrapperToJSON(value?: PostAccountWrapper | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': SaveAccountToJSON(value['account']),
    };
}

