/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { NewTransaction } from './NewTransaction';
import {
    NewTransactionFromJSON,
    NewTransactionFromJSONTyped,
    NewTransactionToJSON,
    NewTransactionToJSONTyped,
} from './NewTransaction';

/**
 * 
 * @export
 * @interface PostTransactionsWrapper
 */
export interface PostTransactionsWrapper {
    /**
     * 
     * @type {NewTransaction}
     * @memberof PostTransactionsWrapper
     */
    transaction?: NewTransaction;
    /**
     * 
     * @type {Array<NewTransaction>}
     * @memberof PostTransactionsWrapper
     */
    transactions?: Array<NewTransaction>;
}

/**
 * Check if a given object implements the PostTransactionsWrapper interface.
 */
export function instanceOfPostTransactionsWrapper(value: object): value is PostTransactionsWrapper {
    return true;
}

export function PostTransactionsWrapperFromJSON(json: any): PostTransactionsWrapper {
    return PostTransactionsWrapperFromJSONTyped(json, false);
}

export function PostTransactionsWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTransactionsWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': json['transaction'] == null ? undefined : NewTransactionFromJSON(json['transaction']),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(NewTransactionFromJSON)),
    };
}

export function PostTransactionsWrapperToJSON(json: any): PostTransactionsWrapper {
    return PostTransactionsWrapperToJSONTyped(json, false);
}

export function PostTransactionsWrapperToJSONTyped(value?: PostTransactionsWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': NewTransactionToJSON(value['transaction']),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(NewTransactionToJSON)),
    };
}

