/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { SaveCategoryGroup } from './SaveCategoryGroup';
import {
    SaveCategoryGroupFromJSON,
    SaveCategoryGroupFromJSONTyped,
    SaveCategoryGroupToJSON,
    SaveCategoryGroupToJSONTyped,
} from './SaveCategoryGroup';

/**
 * 
 * @export
 * @interface PostCategoryGroupWrapper
 */
export interface PostCategoryGroupWrapper {
    /**
     * 
     * @type {SaveCategoryGroup}
     * @memberof PostCategoryGroupWrapper
     */
    category_group: SaveCategoryGroup;
}

/**
 * Check if a given object implements the PostCategoryGroupWrapper interface.
 */
export function instanceOfPostCategoryGroupWrapper(value: object): value is PostCategoryGroupWrapper {
    if (!('category_group' in value) || value['category_group'] === undefined) return false;
    return true;
}

export function PostCategoryGroupWrapperFromJSON(json: any): PostCategoryGroupWrapper {
    return PostCategoryGroupWrapperFromJSONTyped(json, false);
}

export function PostCategoryGroupWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCategoryGroupWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'category_group': SaveCategoryGroupFromJSON(json['category_group']),
    };
}

export function PostCategoryGroupWrapperToJSON(json: any): PostCategoryGroupWrapper {
    return PostCategoryGroupWrapperToJSONTyped(json, false);
}

export function PostCategoryGroupWrapperToJSONTyped(value?: PostCategoryGroupWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category_group': SaveCategoryGroupToJSON(value['category_group']),
    };
}

