/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { NewCategory } from './NewCategory';
import {
    NewCategoryFromJSON,
    NewCategoryFromJSONTyped,
    NewCategoryToJSON,
    NewCategoryToJSONTyped,
} from './NewCategory';

/**
 * 
 * @export
 * @interface PostCategoryWrapper
 */
export interface PostCategoryWrapper {
    /**
     * 
     * @type {NewCategory}
     * @memberof PostCategoryWrapper
     */
    category: NewCategory;
}

/**
 * Check if a given object implements the PostCategoryWrapper interface.
 */
export function instanceOfPostCategoryWrapper(value: object): value is PostCategoryWrapper {
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function PostCategoryWrapperFromJSON(json: any): PostCategoryWrapper {
    return PostCategoryWrapperFromJSONTyped(json, false);
}

export function PostCategoryWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCategoryWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'category': NewCategoryFromJSON(json['category']),
    };
}

export function PostCategoryWrapperToJSON(json: any): PostCategoryWrapper {
    return PostCategoryWrapperToJSONTyped(json, false);
}

export function PostCategoryWrapperToJSONTyped(value?: PostCategoryWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': NewCategoryToJSON(value['category']),
    };
}

