/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPayee
 */
export interface PostPayee {
    /**
     * The name of the payee.
     * @type {string}
     * @memberof PostPayee
     */
    name: string;
}

/**
 * Check if a given object implements the PostPayee interface.
 */
export function instanceOfPostPayee(value: object): value is PostPayee {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PostPayeeFromJSON(json: any): PostPayee {
    return PostPayeeFromJSONTyped(json, false);
}

export function PostPayeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPayee {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function PostPayeeToJSON(json: any): PostPayee {
    return PostPayeeToJSONTyped(json, false);
}

export function PostPayeeToJSONTyped(value?: PostPayee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

