/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payee } from './Payee';
import {
    PayeeFromJSON,
    PayeeFromJSONTyped,
    PayeeToJSON,
} from './Payee';

/**
 * 
 * @export
 * @interface SavePayeeResponseData
 */
export interface SavePayeeResponseData {
    /**
     * 
     * @type {Payee}
     * @memberof SavePayeeResponseData
     */
    payee: Payee;
    /**
     * The knowledge of the server
     * @type {number}
     * @memberof SavePayeeResponseData
     */
    server_knowledge: number;
}

/**
 * Check if a given object implements the SavePayeeResponseData interface.
 */
export function instanceOfSavePayeeResponseData(value: object): value is SavePayeeResponseData {
    if (!('payee' in value) || value['payee'] === undefined) return false;
    if (!('server_knowledge' in value) || value['server_knowledge'] === undefined) return false;
    return true;
}

export function SavePayeeResponseDataFromJSON(json: any): SavePayeeResponseData {
    return SavePayeeResponseDataFromJSONTyped(json, false);
}

export function SavePayeeResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavePayeeResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'payee': PayeeFromJSON(json['payee']),
        'server_knowledge': json['server_knowledge'],
    };
}

export function SavePayeeResponseDataToJSON(value?: SavePayeeResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'payee': PayeeToJSON(value['payee']),
        'server_knowledge': value['server_knowledge'],
    };
}

