/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { SaveCategoryGroupResponseData } from './SaveCategoryGroupResponseData';
import {
    SaveCategoryGroupResponseDataFromJSON,
    SaveCategoryGroupResponseDataFromJSONTyped,
    SaveCategoryGroupResponseDataToJSON,
    SaveCategoryGroupResponseDataToJSONTyped,
} from './SaveCategoryGroupResponseData';

/**
 * 
 * @export
 * @interface SaveCategoryGroupResponse
 */
export interface SaveCategoryGroupResponse {
    /**
     * 
     * @type {SaveCategoryGroupResponseData}
     * @memberof SaveCategoryGroupResponse
     */
    data: SaveCategoryGroupResponseData;
}

/**
 * Check if a given object implements the SaveCategoryGroupResponse interface.
 */
export function instanceOfSaveCategoryGroupResponse(value: object): value is SaveCategoryGroupResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SaveCategoryGroupResponseFromJSON(json: any): SaveCategoryGroupResponse {
    return SaveCategoryGroupResponseFromJSONTyped(json, false);
}

export function SaveCategoryGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveCategoryGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SaveCategoryGroupResponseDataFromJSON(json['data']),
    };
}

export function SaveCategoryGroupResponseToJSON(json: any): SaveCategoryGroupResponse {
    return SaveCategoryGroupResponseToJSONTyped(json, false);
}

export function SaveCategoryGroupResponseToJSONTyped(value?: SaveCategoryGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SaveCategoryGroupResponseDataToJSON(value['data']),
    };
}

