/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveCategory
 */
export interface SaveCategory {
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    category_group_id?: string;
    /**
     * The goal target amount in milliunits format.  This amount can only be changed if the category already has a configured goal (goal_type != null).
     * @type {number}
     * @memberof SaveCategory
     */
    goal_target?: number | null;
}

/**
 * Check if a given object implements the SaveCategory interface.
 */
export function instanceOfSaveCategory(value: object): value is SaveCategory {
    return true;
}

export function SaveCategoryFromJSON(json: any): SaveCategory {
    return SaveCategoryFromJSONTyped(json, false);
}

export function SaveCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'category_group_id': json['category_group_id'] == null ? undefined : json['category_group_id'],
        'goal_target': json['goal_target'] == null ? undefined : json['goal_target'],
    };
}

export function SaveCategoryToJSON(json: any): SaveCategory {
    return SaveCategoryToJSONTyped(json, false);
}

export function SaveCategoryToJSONTyped(value?: SaveCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'note': value['note'],
        'category_group_id': value['category_group_id'],
        'goal_target': value['goal_target'],
    };
}

