/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { SavePayeeResponseData } from './SavePayeeResponseData';
import {
    SavePayeeResponseDataFromJSON,
    SavePayeeResponseDataFromJSONTyped,
    SavePayeeResponseDataToJSON,
} from './SavePayeeResponseData';

/**
 * 
 * @export
 * @interface SavePayeeResponse
 */
export interface SavePayeeResponse {
    /**
     * 
     * @type {SavePayeeResponseData}
     * @memberof SavePayeeResponse
     */
    data: SavePayeeResponseData;
}

/**
 * Check if a given object implements the SavePayeeResponse interface.
 */
export function instanceOfSavePayeeResponse(value: object): value is SavePayeeResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SavePayeeResponseFromJSON(json: any): SavePayeeResponse {
    return SavePayeeResponseFromJSONTyped(json, false);
}

export function SavePayeeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavePayeeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SavePayeeResponseDataFromJSON(json['data']),
    };
}

export function SavePayeeResponseToJSON(value?: SavePayeeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': SavePayeeResponseDataToJSON(value['data']),
    };
}

