/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The scheduled transaction flag
 * @export
 * @interface ScheduledTransactionSummaryFlagColor
 */
export interface ScheduledTransactionSummaryFlagColor {
}

/**
 * Check if a given object implements the ScheduledTransactionSummaryFlagColor interface.
 */
export function instanceOfScheduledTransactionSummaryFlagColor(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScheduledTransactionSummaryFlagColorFromJSON(json: any): ScheduledTransactionSummaryFlagColor {
    return ScheduledTransactionSummaryFlagColorFromJSONTyped(json, false);
}

export function ScheduledTransactionSummaryFlagColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledTransactionSummaryFlagColor {
    return json;
}

export function ScheduledTransactionSummaryFlagColorToJSON(value?: ScheduledTransactionSummaryFlagColor | null): any {
    return value;
}

