/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { TransactionFlagColor } from './TransactionFlagColor';
import {
    TransactionFlagColorFromJSON,
    TransactionFlagColorFromJSONTyped,
    TransactionFlagColorToJSON,
    TransactionFlagColorToJSONTyped,
} from './TransactionFlagColor';

/**
 * 
 * @export
 * @interface ScheduledTransactionSummaryBase
 */
export interface ScheduledTransactionSummaryBase {
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    id: string;
    /**
     * The first date for which the Scheduled Transaction was scheduled.
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    date_first: string;
    /**
     * The next date for which the Scheduled Transaction is scheduled.
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    date_next: string;
    /**
     * 
     * @type {ScheduledTransactionSummaryBaseFrequencyEnum}
     * @memberof ScheduledTransactionSummaryBase
     */
    frequency: ScheduledTransactionSummaryBaseFrequencyEnum;
    /**
     * The scheduled transaction amount in milliunits format
     * @type {number}
     * @memberof ScheduledTransactionSummaryBase
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    memo?: string | null;
    /**
     * 
     * @type {TransactionFlagColor}
     * @memberof ScheduledTransactionSummaryBase
     */
    flag_color?: TransactionFlagColor | null;
    /**
     * The customized name of a transaction flag
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    flag_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    account_id: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    payee_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    category_id?: string | null;
    /**
     * If a transfer, the account_id which the scheduled transaction transfers to
     * @type {string}
     * @memberof ScheduledTransactionSummaryBase
     */
    transfer_account_id?: string | null;
    /**
     * Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
     * @type {boolean}
     * @memberof ScheduledTransactionSummaryBase
     */
    deleted: boolean;
}


/**
 * @export
 */
export const ScheduledTransactionSummaryBaseFrequencyEnum = {
    Never: 'never',
    Daily: 'daily',
    Weekly: 'weekly',
    EveryOtherWeek: 'everyOtherWeek',
    TwiceAMonth: 'twiceAMonth',
    Every4Weeks: 'every4Weeks',
    Monthly: 'monthly',
    EveryOtherMonth: 'everyOtherMonth',
    Every3Months: 'every3Months',
    Every4Months: 'every4Months',
    TwiceAYear: 'twiceAYear',
    Yearly: 'yearly',
    EveryOtherYear: 'everyOtherYear'
} as const;
export type ScheduledTransactionSummaryBaseFrequencyEnum = typeof ScheduledTransactionSummaryBaseFrequencyEnum[keyof typeof ScheduledTransactionSummaryBaseFrequencyEnum];


/**
 * Check if a given object implements the ScheduledTransactionSummaryBase interface.
 */
export function instanceOfScheduledTransactionSummaryBase(value: object): value is ScheduledTransactionSummaryBase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date_first' in value) || value['date_first'] === undefined) return false;
    if (!('date_next' in value) || value['date_next'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function ScheduledTransactionSummaryBaseFromJSON(json: any): ScheduledTransactionSummaryBase {
    return ScheduledTransactionSummaryBaseFromJSONTyped(json, false);
}

export function ScheduledTransactionSummaryBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledTransactionSummaryBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date_first': json['date_first'],
        'date_next': json['date_next'],
        'frequency': json['frequency'],
        'amount': json['amount'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'flag_color': json['flag_color'] == null ? undefined : TransactionFlagColorFromJSON(json['flag_color']),
        'flag_name': json['flag_name'] == null ? undefined : json['flag_name'],
        'account_id': json['account_id'],
        'payee_id': json['payee_id'] == null ? undefined : json['payee_id'],
        'category_id': json['category_id'] == null ? undefined : json['category_id'],
        'transfer_account_id': json['transfer_account_id'] == null ? undefined : json['transfer_account_id'],
        'deleted': json['deleted'],
    };
}

export function ScheduledTransactionSummaryBaseToJSON(json: any): ScheduledTransactionSummaryBase {
    return ScheduledTransactionSummaryBaseToJSONTyped(json, false);
}

export function ScheduledTransactionSummaryBaseToJSONTyped(value?: ScheduledTransactionSummaryBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date_first': value['date_first'],
        'date_next': value['date_next'],
        'frequency': value['frequency'],
        'amount': value['amount'],
        'memo': value['memo'],
        'flag_color': TransactionFlagColorToJSON(value['flag_color']),
        'flag_name': value['flag_name'],
        'account_id': value['account_id'],
        'payee_id': value['payee_id'],
        'category_id': value['category_id'],
        'transfer_account_id': value['transfer_account_id'],
        'deleted': value['deleted'],
    };
}

