/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScheduledTransactionsResponseData } from './ScheduledTransactionsResponseData';
import {
    ScheduledTransactionsResponseDataFromJSON,
    ScheduledTransactionsResponseDataFromJSONTyped,
    ScheduledTransactionsResponseDataToJSON,
} from './ScheduledTransactionsResponseData';

/**
 * 
 * @export
 * @interface ScheduledTransactionsResponse
 */
export interface ScheduledTransactionsResponse {
    /**
     * 
     * @type {ScheduledTransactionsResponseData}
     * @memberof ScheduledTransactionsResponse
     */
    data: ScheduledTransactionsResponseData;
}

/**
 * Check if a given object implements the ScheduledTransactionsResponse interface.
 */
export function instanceOfScheduledTransactionsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ScheduledTransactionsResponseFromJSON(json: any): ScheduledTransactionsResponse {
    return ScheduledTransactionsResponseFromJSONTyped(json, false);
}

export function ScheduledTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledTransactionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ScheduledTransactionsResponseDataFromJSON(json['data']),
    };
}

export function ScheduledTransactionsResponseToJSON(value?: ScheduledTransactionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ScheduledTransactionsResponseDataToJSON(value.data),
    };
}

