/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledSubTransaction
 */
export interface ScheduledSubTransaction {
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    scheduled_transaction_id: string;
    /**
     * The scheduled subtransaction amount in milliunits format
     * @type {number}
     * @memberof ScheduledSubTransaction
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    payee_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    category_id?: string | null;
    /**
     * If a transfer, the account_id which the scheduled subtransaction transfers to
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    transfer_account_id?: string | null;
    /**
     * Whether or not the scheduled subtransaction has been deleted. Deleted scheduled subtransactions will only be included in delta requests.
     * @type {boolean}
     * @memberof ScheduledSubTransaction
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the ScheduledSubTransaction interface.
 */
export function instanceOfScheduledSubTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "scheduled_transaction_id" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "deleted" in value;

    return isInstance;
}

export function ScheduledSubTransactionFromJSON(json: any): ScheduledSubTransaction {
    return ScheduledSubTransactionFromJSONTyped(json, false);
}

export function ScheduledSubTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledSubTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scheduled_transaction_id': json['scheduled_transaction_id'],
        'amount': json['amount'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
        'payee_id': !exists(json, 'payee_id') ? undefined : json['payee_id'],
        'category_id': !exists(json, 'category_id') ? undefined : json['category_id'],
        'transfer_account_id': !exists(json, 'transfer_account_id') ? undefined : json['transfer_account_id'],
        'deleted': json['deleted'],
    };
}

export function ScheduledSubTransactionToJSON(value?: ScheduledSubTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scheduled_transaction_id': value.scheduled_transaction_id,
        'amount': value.amount,
        'memo': value.memo,
        'payee_id': value.payee_id,
        'category_id': value.category_id,
        'transfer_account_id': value.transfer_account_id,
        'deleted': value.deleted,
    };
}

