/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledSubTransaction
 */
export interface ScheduledSubTransaction {
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    scheduled_transaction_id: string;
    /**
     * The scheduled subtransaction amount in milliunits format
     * @type {number}
     * @memberof ScheduledSubTransaction
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    payee_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    payee_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    category_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    category_name?: string | null;
    /**
     * If a transfer, the account_id which the scheduled subtransaction transfers to
     * @type {string}
     * @memberof ScheduledSubTransaction
     */
    transfer_account_id?: string | null;
    /**
     * Whether or not the scheduled subtransaction has been deleted. Deleted scheduled subtransactions will only be included in delta requests.
     * @type {boolean}
     * @memberof ScheduledSubTransaction
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the ScheduledSubTransaction interface.
 */
export function instanceOfScheduledSubTransaction(value: object): value is ScheduledSubTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scheduled_transaction_id' in value) || value['scheduled_transaction_id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function ScheduledSubTransactionFromJSON(json: any): ScheduledSubTransaction {
    return ScheduledSubTransactionFromJSONTyped(json, false);
}

export function ScheduledSubTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledSubTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scheduled_transaction_id': json['scheduled_transaction_id'],
        'amount': json['amount'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'payee_id': json['payee_id'] == null ? undefined : json['payee_id'],
        'payee_name': json['payee_name'] == null ? undefined : json['payee_name'],
        'category_id': json['category_id'] == null ? undefined : json['category_id'],
        'category_name': json['category_name'] == null ? undefined : json['category_name'],
        'transfer_account_id': json['transfer_account_id'] == null ? undefined : json['transfer_account_id'],
        'deleted': json['deleted'],
    };
}

export function ScheduledSubTransactionToJSON(json: any): ScheduledSubTransaction {
    return ScheduledSubTransactionToJSONTyped(json, false);
}

export function ScheduledSubTransactionToJSONTyped(value?: ScheduledSubTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'scheduled_transaction_id': value['scheduled_transaction_id'],
        'amount': value['amount'],
        'memo': value['memo'],
        'payee_id': value['payee_id'],
        'payee_name': value['payee_name'],
        'category_id': value['category_id'],
        'category_name': value['category_name'],
        'transfer_account_id': value['transfer_account_id'],
        'deleted': value['deleted'],
    };
}

