/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubTransactionBase
 */
export interface SubTransactionBase {
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    transaction_id: string;
    /**
     * The subtransaction amount in milliunits format
     * @type {number}
     * @memberof SubTransactionBase
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    payee_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    payee_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    category_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubTransactionBase
     */
    category_name?: string | null;
    /**
     * If a transfer, the account_id which the subtransaction transfers to
     * @type {string}
     * @memberof SubTransactionBase
     */
    transfer_account_id?: string | null;
    /**
     * If a transfer, the id of transaction on the other side of the transfer
     * @type {string}
     * @memberof SubTransactionBase
     */
    transfer_transaction_id?: string | null;
    /**
     * Whether or not the subtransaction has been deleted.  Deleted subtransactions will only be included in delta requests.
     * @type {boolean}
     * @memberof SubTransactionBase
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the SubTransactionBase interface.
 */
export function instanceOfSubTransactionBase(value: object): value is SubTransactionBase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('transaction_id' in value) || value['transaction_id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function SubTransactionBaseFromJSON(json: any): SubTransactionBase {
    return SubTransactionBaseFromJSONTyped(json, false);
}

export function SubTransactionBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubTransactionBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transaction_id': json['transaction_id'],
        'amount': json['amount'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'payee_id': json['payee_id'] == null ? undefined : json['payee_id'],
        'payee_name': json['payee_name'] == null ? undefined : json['payee_name'],
        'category_id': json['category_id'] == null ? undefined : json['category_id'],
        'category_name': json['category_name'] == null ? undefined : json['category_name'],
        'transfer_account_id': json['transfer_account_id'] == null ? undefined : json['transfer_account_id'],
        'transfer_transaction_id': json['transfer_transaction_id'] == null ? undefined : json['transfer_transaction_id'],
        'deleted': json['deleted'],
    };
}

export function SubTransactionBaseToJSON(json: any): SubTransactionBase {
    return SubTransactionBaseToJSONTyped(json, false);
}

export function SubTransactionBaseToJSONTyped(value?: SubTransactionBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transaction_id': value['transaction_id'],
        'amount': value['amount'],
        'memo': value['memo'],
        'payee_id': value['payee_id'],
        'payee_name': value['payee_name'],
        'category_id': value['category_id'],
        'category_name': value['category_name'],
        'transfer_account_id': value['transfer_account_id'],
        'transfer_transaction_id': value['transfer_transaction_id'],
        'deleted': value['deleted'],
    };
}

