/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionSummary
 */
export interface TransactionSummary {
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    id: string;
    /**
     * The transaction date in ISO format (e.g. 2016-12-01)
     * @type {string}
     * @memberof TransactionSummary
     */
    date: string;
    /**
     * The transaction amount in milliunits format
     * @type {number}
     * @memberof TransactionSummary
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    memo?: string | null;
    /**
     * The cleared status of the transaction
     * @type {string}
     * @memberof TransactionSummary
     */
    cleared: TransactionSummaryClearedEnum;
    /**
     * Whether or not the transaction is approved
     * @type {boolean}
     * @memberof TransactionSummary
     */
    approved: boolean;
    /**
     * The transaction flag
     * @type {string}
     * @memberof TransactionSummary
     */
    flag_color?: TransactionSummaryFlagColorEnum;
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    account_id: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    payee_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    category_id?: string | null;
    /**
     * If a transfer transaction, the account to which it transfers
     * @type {string}
     * @memberof TransactionSummary
     */
    transfer_account_id?: string | null;
    /**
     * If a transfer transaction, the id of transaction on the other side of the transfer
     * @type {string}
     * @memberof TransactionSummary
     */
    transfer_transaction_id?: string | null;
    /**
     * If transaction is matched, the id of the matched transaction
     * @type {string}
     * @memberof TransactionSummary
     */
    matched_transaction_id?: string | null;
    /**
     * If the transaction was imported, this field is a unique (by account) import identifier.  If this transaction was imported through File Based Import or Direct Import and not through the API, the import_id will have the format: 'YNAB:[milliunit_amount]:[iso_date]:[occurrence]'.  For example, a transaction dated 2015-12-30 in the amount of -$294.23 USD would have an import_id of 'YNAB:-294230:2015-12-30:1'.  If a second transaction on the same account was imported and had the same date and same amount, its import_id would be 'YNAB:-294230:2015-12-30:2'.
     * @type {string}
     * @memberof TransactionSummary
     */
    import_id?: string | null;
    /**
     * If the transaction was imported, the payee name that was used when importing and before applying any payee rename rules
     * @type {string}
     * @memberof TransactionSummary
     */
    import_payee_name?: string | null;
    /**
     * If the transaction was imported, the original payee name as it appeared on the statement
     * @type {string}
     * @memberof TransactionSummary
     */
    import_payee_name_original?: string | null;
    /**
     * If the transaction is a debt/loan account transaction, the type of transaction
     * @type {string}
     * @memberof TransactionSummary
     */
    debt_transaction_type?: TransactionSummaryDebtTransactionTypeEnum;
    /**
     * Whether or not the transaction has been deleted.  Deleted transactions will only be included in delta requests.
     * @type {boolean}
     * @memberof TransactionSummary
     */
    deleted: boolean;
}


/**
 * @export
 */
export const TransactionSummaryClearedEnum = {
    Cleared: 'cleared',
    Uncleared: 'uncleared',
    Reconciled: 'reconciled'
} as const;
export type TransactionSummaryClearedEnum = typeof TransactionSummaryClearedEnum[keyof typeof TransactionSummaryClearedEnum];

/**
 * @export
 */
export const TransactionSummaryFlagColorEnum = {
    Red: 'red',
    Orange: 'orange',
    Yellow: 'yellow',
    Green: 'green',
    Blue: 'blue',
    Purple: 'purple',
    Null: 'null'
} as const;
export type TransactionSummaryFlagColorEnum = typeof TransactionSummaryFlagColorEnum[keyof typeof TransactionSummaryFlagColorEnum];

/**
 * @export
 */
export const TransactionSummaryDebtTransactionTypeEnum = {
    Payment: 'payment',
    Refund: 'refund',
    Fee: 'fee',
    Interest: 'interest',
    Escrow: 'escrow',
    BalancedAdjustment: 'balancedAdjustment',
    Credit: 'credit',
    Charge: 'charge',
    Null: 'null'
} as const;
export type TransactionSummaryDebtTransactionTypeEnum = typeof TransactionSummaryDebtTransactionTypeEnum[keyof typeof TransactionSummaryDebtTransactionTypeEnum];


/**
 * Check if a given object implements the TransactionSummary interface.
 */
export function instanceOfTransactionSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "cleared" in value;
    isInstance = isInstance && "approved" in value;
    isInstance = isInstance && "account_id" in value;
    isInstance = isInstance && "deleted" in value;

    return isInstance;
}

export function TransactionSummaryFromJSON(json: any): TransactionSummary {
    return TransactionSummaryFromJSONTyped(json, false);
}

export function TransactionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'amount': json['amount'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
        'cleared': json['cleared'],
        'approved': json['approved'],
        'flag_color': !exists(json, 'flag_color') ? undefined : json['flag_color'],
        'account_id': json['account_id'],
        'payee_id': !exists(json, 'payee_id') ? undefined : json['payee_id'],
        'category_id': !exists(json, 'category_id') ? undefined : json['category_id'],
        'transfer_account_id': !exists(json, 'transfer_account_id') ? undefined : json['transfer_account_id'],
        'transfer_transaction_id': !exists(json, 'transfer_transaction_id') ? undefined : json['transfer_transaction_id'],
        'matched_transaction_id': !exists(json, 'matched_transaction_id') ? undefined : json['matched_transaction_id'],
        'import_id': !exists(json, 'import_id') ? undefined : json['import_id'],
        'import_payee_name': !exists(json, 'import_payee_name') ? undefined : json['import_payee_name'],
        'import_payee_name_original': !exists(json, 'import_payee_name_original') ? undefined : json['import_payee_name_original'],
        'debt_transaction_type': !exists(json, 'debt_transaction_type') ? undefined : json['debt_transaction_type'],
        'deleted': json['deleted'],
    };
}

export function TransactionSummaryToJSON(value?: TransactionSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'date': value.date,
        'amount': value.amount,
        'memo': value.memo,
        'cleared': value.cleared,
        'approved': value.approved,
        'flag_color': value.flag_color,
        'account_id': value.account_id,
        'payee_id': value.payee_id,
        'category_id': value.category_id,
        'transfer_account_id': value.transfer_account_id,
        'transfer_transaction_id': value.transfer_transaction_id,
        'matched_transaction_id': value.matched_transaction_id,
        'import_id': value.import_id,
        'import_payee_name': value.import_payee_name,
        'import_payee_name_original': value.import_payee_name_original,
        'debt_transaction_type': value.debt_transaction_type,
        'deleted': value.deleted,
    };
}

