/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The transaction flag
 * @export
 */
export const TransactionFlagColor = {
    Red: 'red',
    Orange: 'orange',
    Yellow: 'yellow',
    Green: 'green',
    Blue: 'blue',
    Purple: 'purple',
    
} as const;
export type TransactionFlagColor = typeof TransactionFlagColor[keyof typeof TransactionFlagColor];


export function TransactionFlagColorFromJSON(json: any): TransactionFlagColor {
    return TransactionFlagColorFromJSONTyped(json, false);
}

export function TransactionFlagColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionFlagColor {
    return json as TransactionFlagColor;
}

export function TransactionFlagColorToJSON(value?: TransactionFlagColor | null): any {
    return value as any;
}

