/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { TransactionsImportResponseData } from './TransactionsImportResponseData';
import {
    TransactionsImportResponseDataFromJSON,
    TransactionsImportResponseDataFromJSONTyped,
    TransactionsImportResponseDataToJSON,
    TransactionsImportResponseDataToJSONTyped,
} from './TransactionsImportResponseData';

/**
 * 
 * @export
 * @interface TransactionsImportResponse
 */
export interface TransactionsImportResponse {
    /**
     * 
     * @type {TransactionsImportResponseData}
     * @memberof TransactionsImportResponse
     */
    data: TransactionsImportResponseData;
}

/**
 * Check if a given object implements the TransactionsImportResponse interface.
 */
export function instanceOfTransactionsImportResponse(value: object): value is TransactionsImportResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TransactionsImportResponseFromJSON(json: any): TransactionsImportResponse {
    return TransactionsImportResponseFromJSONTyped(json, false);
}

export function TransactionsImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsImportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TransactionsImportResponseDataFromJSON(json['data']),
    };
}

export function TransactionsImportResponseToJSON(json: any): TransactionsImportResponse {
    return TransactionsImportResponseToJSONTyped(json, false);
}

export function TransactionsImportResponseToJSONTyped(value?: TransactionsImportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TransactionsImportResponseDataToJSON(value['data']),
    };
}

