/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */


/**
 * The cleared status of the transaction
 * @export
 */
export const TransactionClearedStatus = {
    Cleared: 'cleared',
    Uncleared: 'uncleared',
    Reconciled: 'reconciled'
} as const;
export type TransactionClearedStatus = typeof TransactionClearedStatus[keyof typeof TransactionClearedStatus];


export function instanceOfTransactionClearedStatus(value: any): boolean {
    for (const key in TransactionClearedStatus) {
        if (Object.prototype.hasOwnProperty.call(TransactionClearedStatus, key)) {
            if (TransactionClearedStatus[key as keyof typeof TransactionClearedStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionClearedStatusFromJSON(json: any): TransactionClearedStatus {
    return TransactionClearedStatusFromJSONTyped(json, false);
}

export function TransactionClearedStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionClearedStatus {
    return json as TransactionClearedStatus;
}

export function TransactionClearedStatusToJSON(value?: TransactionClearedStatus | null): any {
    return value as any;
}

export function TransactionClearedStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionClearedStatus {
    return value as TransactionClearedStatus;
}

