/* tslint:disable */
/* eslint-disable */
/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

import { mapValues } from '../runtime';
import type { TransactionFlagColor } from './TransactionFlagColor';
import {
    TransactionFlagColorFromJSON,
    TransactionFlagColorFromJSONTyped,
    TransactionFlagColorToJSON,
} from './TransactionFlagColor';
import type { TransactionClearedStatus } from './TransactionClearedStatus';
import {
    TransactionClearedStatusFromJSON,
    TransactionClearedStatusFromJSONTyped,
    TransactionClearedStatusToJSON,
} from './TransactionClearedStatus';
import type { SubTransaction } from './SubTransaction';
import {
    SubTransactionFromJSON,
    SubTransactionFromJSONTyped,
    SubTransactionToJSON,
} from './SubTransaction';

/**
 * 
 * @export
 * @interface TransactionDetail
 */
export interface TransactionDetail {
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    id: string;
    /**
     * The transaction date in ISO format (e.g. 2016-12-01)
     * @type {string}
     * @memberof TransactionDetail
     */
    date: string;
    /**
     * The transaction amount in milliunits format
     * @type {number}
     * @memberof TransactionDetail
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    memo?: string;
    /**
     * 
     * @type {TransactionClearedStatus}
     * @memberof TransactionDetail
     */
    cleared: TransactionClearedStatus;
    /**
     * Whether or not the transaction is approved
     * @type {boolean}
     * @memberof TransactionDetail
     */
    approved: boolean;
    /**
     * 
     * @type {TransactionFlagColor}
     * @memberof TransactionDetail
     */
    flag_color?: TransactionFlagColor;
    /**
     * The customized name of a transaction flag
     * @type {string}
     * @memberof TransactionDetail
     */
    flag_name?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    account_id: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    payee_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    category_id?: string;
    /**
     * If a transfer transaction, the account to which it transfers
     * @type {string}
     * @memberof TransactionDetail
     */
    transfer_account_id?: string;
    /**
     * If a transfer transaction, the id of transaction on the other side of the transfer
     * @type {string}
     * @memberof TransactionDetail
     */
    transfer_transaction_id?: string;
    /**
     * If transaction is matched, the id of the matched transaction
     * @type {string}
     * @memberof TransactionDetail
     */
    matched_transaction_id?: string;
    /**
     * If the transaction was imported, this field is a unique (by account) import identifier.  If this transaction was imported through File Based Import or Direct Import and not through the API, the import_id will have the format: 'YNAB:[milliunit_amount]:[iso_date]:[occurrence]'.  For example, a transaction dated 2015-12-30 in the amount of -$294.23 USD would have an import_id of 'YNAB:-294230:2015-12-30:1'.  If a second transaction on the same account was imported and had the same date and same amount, its import_id would be 'YNAB:-294230:2015-12-30:2'.
     * @type {string}
     * @memberof TransactionDetail
     */
    import_id?: string;
    /**
     * If the transaction was imported, the payee name that was used when importing and before applying any payee rename rules
     * @type {string}
     * @memberof TransactionDetail
     */
    import_payee_name?: string;
    /**
     * If the transaction was imported, the original payee name as it appeared on the statement
     * @type {string}
     * @memberof TransactionDetail
     */
    import_payee_name_original?: string;
    /**
     * If the transaction is a debt/loan account transaction, the type of transaction
     * @type {string}
     * @memberof TransactionDetail
     */
    debt_transaction_type?: TransactionDetailDebtTransactionTypeEnum;
    /**
     * Whether or not the transaction has been deleted.  Deleted transactions will only be included in delta requests.
     * @type {boolean}
     * @memberof TransactionDetail
     */
    deleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    account_name: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionDetail
     */
    payee_name?: string;
    /**
     * The name of the category.  If a split transaction, this will be 'Split'.
     * @type {string}
     * @memberof TransactionDetail
     */
    category_name?: string;
    /**
     * If a split transaction, the subtransactions.
     * @type {Array<SubTransaction>}
     * @memberof TransactionDetail
     */
    subtransactions: Array<SubTransaction>;
}


/**
 * @export
 */
export const TransactionDetailDebtTransactionTypeEnum = {
    Payment: 'payment',
    Refund: 'refund',
    Fee: 'fee',
    Interest: 'interest',
    Escrow: 'escrow',
    BalanceAdjustment: 'balanceAdjustment',
    Credit: 'credit',
    Charge: 'charge',
    
} as const;
export type TransactionDetailDebtTransactionTypeEnum = typeof TransactionDetailDebtTransactionTypeEnum[keyof typeof TransactionDetailDebtTransactionTypeEnum];


/**
 * Check if a given object implements the TransactionDetail interface.
 */
export function instanceOfTransactionDetail(value: object): value is TransactionDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('cleared' in value) || value['cleared'] === undefined) return false;
    if (!('approved' in value) || value['approved'] === undefined) return false;
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('account_name' in value) || value['account_name'] === undefined) return false;
    if (!('subtransactions' in value) || value['subtransactions'] === undefined) return false;
    return true;
}

export function TransactionDetailFromJSON(json: any): TransactionDetail {
    return TransactionDetailFromJSONTyped(json, false);
}

export function TransactionDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'amount': json['amount'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'cleared': TransactionClearedStatusFromJSON(json['cleared']),
        'approved': json['approved'],
        'flag_color': json['flag_color'] == null ? undefined : TransactionFlagColorFromJSON(json['flag_color']),
        'flag_name': json['flag_name'] == null ? undefined : json['flag_name'],
        'account_id': json['account_id'],
        'payee_id': json['payee_id'] == null ? undefined : json['payee_id'],
        'category_id': json['category_id'] == null ? undefined : json['category_id'],
        'transfer_account_id': json['transfer_account_id'] == null ? undefined : json['transfer_account_id'],
        'transfer_transaction_id': json['transfer_transaction_id'] == null ? undefined : json['transfer_transaction_id'],
        'matched_transaction_id': json['matched_transaction_id'] == null ? undefined : json['matched_transaction_id'],
        'import_id': json['import_id'] == null ? undefined : json['import_id'],
        'import_payee_name': json['import_payee_name'] == null ? undefined : json['import_payee_name'],
        'import_payee_name_original': json['import_payee_name_original'] == null ? undefined : json['import_payee_name_original'],
        'debt_transaction_type': json['debt_transaction_type'] == null ? undefined : json['debt_transaction_type'],
        'deleted': json['deleted'],
        'account_name': json['account_name'],
        'payee_name': json['payee_name'] == null ? undefined : json['payee_name'],
        'category_name': json['category_name'] == null ? undefined : json['category_name'],
        'subtransactions': ((json['subtransactions'] as Array<any>).map(SubTransactionFromJSON)),
    };
}

export function TransactionDetailToJSON(value?: TransactionDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'date': value['date'],
        'amount': value['amount'],
        'memo': value['memo'],
        'cleared': TransactionClearedStatusToJSON(value['cleared']),
        'approved': value['approved'],
        'flag_color': TransactionFlagColorToJSON(value['flag_color']),
        'flag_name': value['flag_name'],
        'account_id': value['account_id'],
        'payee_id': value['payee_id'],
        'category_id': value['category_id'],
        'transfer_account_id': value['transfer_account_id'],
        'transfer_transaction_id': value['transfer_transaction_id'],
        'matched_transaction_id': value['matched_transaction_id'],
        'import_id': value['import_id'],
        'import_payee_name': value['import_payee_name'],
        'import_payee_name_original': value['import_payee_name_original'],
        'debt_transaction_type': value['debt_transaction_type'],
        'deleted': value['deleted'],
        'account_name': value['account_name'],
        'payee_name': value['payee_name'],
        'category_name': value['category_name'],
        'subtransactions': ((value['subtransactions'] as Array<any>).map(SubTransactionToJSON)),
    };
}

