// tslint:disable
/**
 * YNAB API Explorer
 * A read-only JSON / REST API to access YNAB budget data.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class Configuration {
    /**
     * API Key
     * @memberof Configuration
     */
    apiKey: string;
    /**
     * The API base path
     *
     * @type {string}
     * @memberof Configuration
     */
    basePath: string;

    constructor(accessToken: string, basePath: string) {
        this.apiKey = `Bearer ${accessToken}`;
        this.basePath = basePath;
    }
}
