name: Socket Basics Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  socket-basics-security-scan:
    uses: ynab/ynab-sast-scanner/.github/workflows/socket-basics.yml@main
    secrets:
      SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
      SAST_SUPPRESSIONS_APP_PRIVATE_KEY: ${{ secrets.SAST_SUPPRESSIONS_APP_PRIVATE_KEY }}
